"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _PromiseState = require("./PromiseState");

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } }

function _createClass(Constructor, protoProps, staticProps) { if (protoProps) _defineProperties(Constructor.prototype, protoProps); if (staticProps) _defineProperties(Constructor, staticProps); return Constructor; }

function _defineProperty(obj, key, value) { if (key in obj) { Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true }); } else { obj[key] = value; } return obj; }

// 1.1. “promise” is an object or function with a then method whose behavior conforms to the Promises/A+ specification.
var MyPromise =
/*#__PURE__*/
function () {
  function MyPromise() {
    var executor = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : null;

    _classCallCheck(this, MyPromise);

    _defineProperty(this, "value", void 0);

    _defineProperty(this, "state", void 0);

    _defineProperty(this, "onFulfilledHandler", void 0);

    _defineProperty(this, "onRejectedHandler", void 0);

    _defineProperty(this, "promiseSettlementQueue", void 0);

    this.value = null; // default promise value as null

    this.state = _PromiseState.PromiseState.PENDING; // default promise state as pending
    // register default handlers for promise on fulfillment and rejection

    this.onFulfilledHandler = function (value) {
      return value;
    };

    this.onRejectedHandler = function (reason) {
      throw reason;
    }; // create an empty promise settlement queue for promises generated by then calls


    this.promiseSettlementQueue = []; // bind executor resolve reject callbacks

    if (executor) {
      executor(function (value) {
        /** @todo Promise Resolution Procedure */
      }, function (reason) {
        /** @todo Promise Rejection Procedure */
      });
    }
  }
  /**
   * 2.2.1 Both onFulfilled and onRejected are optional arguments:
   *
   * @param onFulfilled
   * @param onRejected
   */


  _createClass(MyPromise, [{
    key: "then",
    value: function then(onFulfilled, onRejected) {
      // create a new promise to be returned by then for promise chaining
      var promise = new MyPromise(); // 2.2.1.1 If onFulfilled is not a function, it must be ignored.

      if (typeof onFulfilled === "function") {
        promise.onFulfilledHandler = onFulfilled;
      } // 2.2.1.2 If onRejected is not a function, it must be ignored.


      if (typeof onRejected === "function") {
        promise.onFulfilledHandler = onRejected;
      }
      /**
       * 2.2.6. then may be called multiple times on the same promise.
       *   2.2.6.1. If/when promise is fulfilled, all respective onFulfilled
       *     callbacks must execute in the order of their originating calls to then.
       *   2.2.6.2. If/when promise is rejected, all respective onRejected
       *     callbacks must execute in the order of their originating calls to then.
       */


      this.promiseSettlementQueue.push(promise);
      this.processRegisteredHandlers(); // 2.2.7. then must return a promise

      return promise;
    }
    /**
     * 2.1.1. When pending, a promise:
     *   2.1.1.1. may transition to either the fulfilled or rejected state.
     * 2.1.2. When fulfilled, a promise:
     *   2.1.2.1. must not transition to any other state.
     *   2.1.2.2. must have a value, which must not change.
     * 2.1.3. When rejected, a promise:
     *   2.1.3.1. must not transition to any other state.
     *   2.1.3.2. must have a reason, which must not change.
     *
     * @param state state to transition to
     * @param value value passed with the transition for
     */

  }, {
    key: "transitionState",
    value: function transitionState(state, value) {
      if (this.state === state || this.state !== _PromiseState.PromiseState.PENDING) {
        // if the current state is same as the state being transitioned to
        // or the promise is not currently in pending state
        // do nothing
        return;
      }

      this.value = value;
      this.state = state;
      this.processRegisteredHandlers();
    }
    /**
     * reject
     * @param reason can by anything but generally an Error object
     */

  }, {
    key: "reject",
    value: function reject(reason) {
      this.transitionState(_PromiseState.PromiseState.REJECTED, reason);
    }
  }, {
    key: "processRegisteredHandlers",
    value: function processRegisteredHandlers() {
      var _this = this;

      if (this.state !== _PromiseState.PromiseState.PENDING) {
        // 2.2.4 onFulfilled or onRejected must not be called
        // until the execution context stack contains only platform code.
        setTimeout(function () {
          // 2.2.7. then may be called multiple times on the same promise.
          //   2.2.6.1. If/when promise is fulfilled,
          //     all respective onFulfilled callbacks must execute in the
          //     order of their originating calls to then.
          //   2.2.6.2. If/when promise is rejected,
          //     all respective onRejected callbacks must execute in the
          //     order of their originating calls to then.
          // this is acheived by dequeue on FIFO data structure (i.e. queue)
          while (_this.promiseSettlementQueue.length) {
            // dequeue
            var promise = _this.promiseSettlementQueue.shift();

            try {
              // 2.2.5. onFulfilled and onRejected must be called as functions (i.e. with no this value).
              var value = (_this.state === _PromiseState.PromiseState.FULFILLED ? promise.onFulfilled : promise.onRejected)(_this.value); // 2.2.7.1. If either onFulfilled or onRejected returns a value x,
              // run the Promise Resolution Procedure [[Resolve]](promise2, x).

              /** @todo Promise Resolution Procedure */
            } catch (e) {// 2.2.7.2. If either onFulfilled or onRejected throws an exception e,
              // promise2 must be rejected with e as the reason.

              /** @todo Promise Rejection Procedure */
            }
          }
        }, 0);
      }
    }
  }]);

  return MyPromise;
}();

exports.default = MyPromise;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi4uL3NyYy9NeVByb21pc2UudHMiXSwibmFtZXMiOlsiTXlQcm9taXNlIiwiZXhlY3V0b3IiLCJ2YWx1ZSIsInN0YXRlIiwiUHJvbWlzZVN0YXRlIiwiUEVORElORyIsIm9uRnVsZmlsbGVkSGFuZGxlciIsIm9uUmVqZWN0ZWRIYW5kbGVyIiwicmVhc29uIiwicHJvbWlzZVNldHRsZW1lbnRRdWV1ZSIsIm9uRnVsZmlsbGVkIiwib25SZWplY3RlZCIsInByb21pc2UiLCJwdXNoIiwicHJvY2Vzc1JlZ2lzdGVyZWRIYW5kbGVycyIsInRyYW5zaXRpb25TdGF0ZSIsIlJFSkVDVEVEIiwic2V0VGltZW91dCIsImxlbmd0aCIsInNoaWZ0IiwiRlVMRklMTEVEIiwiZSJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7QUFFQTs7Ozs7Ozs7OztBQUdBO0lBQ3FCQSxTOzs7QUFVbkIsdUJBQW1EO0FBQUEsUUFBdkNDLFFBQXVDLHVFQUFOLElBQU07O0FBQUE7O0FBQUE7O0FBQUE7O0FBQUE7O0FBQUE7O0FBQUE7O0FBQ2pELFNBQUtDLEtBQUwsR0FBYSxJQUFiLENBRGlELENBQzlCOztBQUNuQixTQUFLQyxLQUFMLEdBQWFDLDJCQUFhQyxPQUExQixDQUZpRCxDQUVkO0FBRW5DOztBQUNBLFNBQUtDLGtCQUFMLEdBQTBCLFVBQUNKLEtBQUQ7QUFBQSxhQUFnQkEsS0FBaEI7QUFBQSxLQUExQjs7QUFDQSxTQUFLSyxpQkFBTCxHQUF5QixVQUFDQyxNQUFELEVBQXVCO0FBQUUsWUFBTUEsTUFBTjtBQUFlLEtBQWpFLENBTmlELENBUWpEOzs7QUFDQSxTQUFLQyxzQkFBTCxHQUE4QixFQUE5QixDQVRpRCxDQVdqRDs7QUFDQSxRQUFJUixRQUFKLEVBQWM7QUFDWkEsTUFBQUEsUUFBUSxDQUFDLFVBQUNDLEtBQUQsRUFBZ0I7QUFDdkI7QUFDRCxPQUZPLEVBRUwsVUFBQ00sTUFBRCxFQUFpQjtBQUNsQjtBQUNELE9BSk8sQ0FBUjtBQUtEO0FBQ0Y7QUFFRDs7Ozs7Ozs7Ozt5QkFNWUUsVyxFQUFrQkMsVSxFQUE0QjtBQUN4RDtBQUNBLFVBQU1DLE9BQWtCLEdBQUcsSUFBSVosU0FBSixFQUEzQixDQUZ3RCxDQUl4RDs7QUFDQSxVQUFJLE9BQU9VLFdBQVAsS0FBdUIsVUFBM0IsRUFBdUM7QUFDckNFLFFBQUFBLE9BQU8sQ0FBQ04sa0JBQVIsR0FBNkJJLFdBQTdCO0FBQ0QsT0FQdUQsQ0FTeEQ7OztBQUNBLFVBQUksT0FBT0MsVUFBUCxLQUFzQixVQUExQixFQUFzQztBQUNwQ0MsUUFBQUEsT0FBTyxDQUFDTixrQkFBUixHQUE2QkssVUFBN0I7QUFDRDtBQUVEOzs7Ozs7Ozs7QUFPQSxXQUFLRixzQkFBTCxDQUE0QkksSUFBNUIsQ0FBaUNELE9BQWpDO0FBQ0EsV0FBS0UseUJBQUwsR0F0QndELENBd0J4RDs7QUFDQSxhQUFPRixPQUFQO0FBQ0Q7QUFFRDs7Ozs7Ozs7Ozs7Ozs7OztvQ0FhdUJULEssRUFBcUJELEssRUFBa0I7QUFFNUQsVUFBSSxLQUFLQyxLQUFMLEtBQWVBLEtBQWYsSUFBd0IsS0FBS0EsS0FBTCxLQUFlQywyQkFBYUMsT0FBeEQsRUFBaUU7QUFDL0Q7QUFDQTtBQUNBO0FBQ0E7QUFDRDs7QUFFRCxXQUFLSCxLQUFMLEdBQWFBLEtBQWI7QUFDQSxXQUFLQyxLQUFMLEdBQWFBLEtBQWI7QUFFQSxXQUFLVyx5QkFBTDtBQUNEO0FBRUQ7Ozs7Ozs7MkJBSWNOLE0sRUFBeUI7QUFDckMsV0FBS08sZUFBTCxDQUFxQlgsMkJBQWFZLFFBQWxDLEVBQTRDUixNQUE1QztBQUNEOzs7Z0RBRXlDO0FBQUE7O0FBQ3hDLFVBQUksS0FBS0wsS0FBTCxLQUFlQywyQkFBYUMsT0FBaEMsRUFBeUM7QUFDdkM7QUFDQTtBQUNBWSxRQUFBQSxVQUFVLENBQUMsWUFBTTtBQUVmO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQSxpQkFBTyxLQUFJLENBQUNSLHNCQUFMLENBQTRCUyxNQUFuQyxFQUEyQztBQUN6QztBQUNBLGdCQUFNTixPQUFzQixHQUFHLEtBQUksQ0FBQ0gsc0JBQUwsQ0FBNEJVLEtBQTVCLEVBQS9COztBQUVBLGdCQUFJO0FBQ0Y7QUFDQSxrQkFBTWpCLEtBQUssR0FBRyxDQUNaLEtBQUksQ0FBQ0MsS0FBTCxLQUFlQywyQkFBYWdCLFNBQTVCLEdBQXdDUixPQUFPLENBQUNGLFdBQWhELEdBQThERSxPQUFPLENBQUNELFVBRDFELEVBRVosS0FBSSxDQUFDVCxLQUZPLENBQWQsQ0FGRSxDQUtGO0FBQ0E7O0FBQ0E7QUFDRCxhQVJELENBUUUsT0FBT21CLENBQVAsRUFBVSxDQUNWO0FBQ0E7O0FBQ0E7QUFDRDtBQUNGO0FBQ0YsU0E1QlMsRUE0QlAsQ0E1Qk8sQ0FBVjtBQTZCRDtBQUNGIiwic291cmNlc0NvbnRlbnQiOlsiXCJ1c2Ugc3RyaWN0XCI7XG5cbmltcG9ydCB7IFByb21pc2VTdGF0ZSB9IGZyb20gXCIuL1Byb21pc2VTdGF0ZVwiO1xuaW1wb3J0IFRoZW5hYmxlIGZyb20gXCIuL1RoZW5hYmxlXCI7XG5cbi8vIDEuMS4g4oCccHJvbWlzZeKAnSBpcyBhbiBvYmplY3Qgb3IgZnVuY3Rpb24gd2l0aCBhIHRoZW4gbWV0aG9kIHdob3NlIGJlaGF2aW9yIGNvbmZvcm1zIHRvIHRoZSBQcm9taXNlcy9BKyBzcGVjaWZpY2F0aW9uLlxuZXhwb3J0IGRlZmF1bHQgY2xhc3MgTXlQcm9taXNlIGltcGxlbWVudHMgVGhlbmFibGUge1xuXG4gIHByaXZhdGUgdmFsdWU6IGFueTtcbiAgcHJpdmF0ZSBzdGF0ZTogUHJvbWlzZVN0YXRlO1xuXG4gIHByaXZhdGUgb25GdWxmaWxsZWRIYW5kbGVyOiBDYWxsYWJsZUZ1bmN0aW9uO1xuICBwcml2YXRlIG9uUmVqZWN0ZWRIYW5kbGVyOiBDYWxsYWJsZUZ1bmN0aW9uO1xuXG4gIHByaXZhdGUgcHJvbWlzZVNldHRsZW1lbnRRdWV1ZTogTXlQcm9taXNlW107XG5cbiAgY29uc3RydWN0b3IoZXhlY3V0b3I6IENhbGxhYmxlRnVuY3Rpb258YW55ID0gbnVsbCkge1xuICAgIHRoaXMudmFsdWUgPSBudWxsOyAvLyBkZWZhdWx0IHByb21pc2UgdmFsdWUgYXMgbnVsbFxuICAgIHRoaXMuc3RhdGUgPSBQcm9taXNlU3RhdGUuUEVORElORzsgLy8gZGVmYXVsdCBwcm9taXNlIHN0YXRlIGFzIHBlbmRpbmdcblxuICAgIC8vIHJlZ2lzdGVyIGRlZmF1bHQgaGFuZGxlcnMgZm9yIHByb21pc2Ugb24gZnVsZmlsbG1lbnQgYW5kIHJlamVjdGlvblxuICAgIHRoaXMub25GdWxmaWxsZWRIYW5kbGVyID0gKHZhbHVlOiBhbnkpID0+IHZhbHVlO1xuICAgIHRoaXMub25SZWplY3RlZEhhbmRsZXIgPSAocmVhc29uOiBFcnJvcnxhbnkpID0+IHsgdGhyb3cgcmVhc29uOyB9O1xuXG4gICAgLy8gY3JlYXRlIGFuIGVtcHR5IHByb21pc2Ugc2V0dGxlbWVudCBxdWV1ZSBmb3IgcHJvbWlzZXMgZ2VuZXJhdGVkIGJ5IHRoZW4gY2FsbHNcbiAgICB0aGlzLnByb21pc2VTZXR0bGVtZW50UXVldWUgPSBbXTtcblxuICAgIC8vIGJpbmQgZXhlY3V0b3IgcmVzb2x2ZSByZWplY3QgY2FsbGJhY2tzXG4gICAgaWYgKGV4ZWN1dG9yKSB7XG4gICAgICBleGVjdXRvcigodmFsdWU6IGFueSkgPT4ge1xuICAgICAgICAvKiogQHRvZG8gUHJvbWlzZSBSZXNvbHV0aW9uIFByb2NlZHVyZSAqL1xuICAgICAgfSwgKHJlYXNvbjogYW55KSA9PiB7XG4gICAgICAgIC8qKiBAdG9kbyBQcm9taXNlIFJlamVjdGlvbiBQcm9jZWR1cmUgKi9cbiAgICAgIH0pO1xuICAgIH1cbiAgfVxuXG4gIC8qKlxuICAgKiAyLjIuMSBCb3RoIG9uRnVsZmlsbGVkIGFuZCBvblJlamVjdGVkIGFyZSBvcHRpb25hbCBhcmd1bWVudHM6XG4gICAqXG4gICAqIEBwYXJhbSBvbkZ1bGZpbGxlZFxuICAgKiBAcGFyYW0gb25SZWplY3RlZFxuICAgKi9cbiAgcHVibGljIHRoZW4ob25GdWxmaWxsZWQ6IGFueSwgb25SZWplY3RlZDogYW55KTogTXlQcm9taXNlIHtcbiAgICAvLyBjcmVhdGUgYSBuZXcgcHJvbWlzZSB0byBiZSByZXR1cm5lZCBieSB0aGVuIGZvciBwcm9taXNlIGNoYWluaW5nXG4gICAgY29uc3QgcHJvbWlzZTogTXlQcm9taXNlID0gbmV3IE15UHJvbWlzZSgpO1xuXG4gICAgLy8gMi4yLjEuMSBJZiBvbkZ1bGZpbGxlZCBpcyBub3QgYSBmdW5jdGlvbiwgaXQgbXVzdCBiZSBpZ25vcmVkLlxuICAgIGlmICh0eXBlb2Ygb25GdWxmaWxsZWQgPT09IFwiZnVuY3Rpb25cIikge1xuICAgICAgcHJvbWlzZS5vbkZ1bGZpbGxlZEhhbmRsZXIgPSBvbkZ1bGZpbGxlZDtcbiAgICB9XG5cbiAgICAvLyAyLjIuMS4yIElmIG9uUmVqZWN0ZWQgaXMgbm90IGEgZnVuY3Rpb24sIGl0IG11c3QgYmUgaWdub3JlZC5cbiAgICBpZiAodHlwZW9mIG9uUmVqZWN0ZWQgPT09IFwiZnVuY3Rpb25cIikge1xuICAgICAgcHJvbWlzZS5vbkZ1bGZpbGxlZEhhbmRsZXIgPSBvblJlamVjdGVkO1xuICAgIH1cblxuICAgIC8qKlxuICAgICAqIDIuMi42LiB0aGVuIG1heSBiZSBjYWxsZWQgbXVsdGlwbGUgdGltZXMgb24gdGhlIHNhbWUgcHJvbWlzZS5cbiAgICAgKiAgIDIuMi42LjEuIElmL3doZW4gcHJvbWlzZSBpcyBmdWxmaWxsZWQsIGFsbCByZXNwZWN0aXZlIG9uRnVsZmlsbGVkXG4gICAgICogICAgIGNhbGxiYWNrcyBtdXN0IGV4ZWN1dGUgaW4gdGhlIG9yZGVyIG9mIHRoZWlyIG9yaWdpbmF0aW5nIGNhbGxzIHRvIHRoZW4uXG4gICAgICogICAyLjIuNi4yLiBJZi93aGVuIHByb21pc2UgaXMgcmVqZWN0ZWQsIGFsbCByZXNwZWN0aXZlIG9uUmVqZWN0ZWRcbiAgICAgKiAgICAgY2FsbGJhY2tzIG11c3QgZXhlY3V0ZSBpbiB0aGUgb3JkZXIgb2YgdGhlaXIgb3JpZ2luYXRpbmcgY2FsbHMgdG8gdGhlbi5cbiAgICAgKi9cbiAgICB0aGlzLnByb21pc2VTZXR0bGVtZW50UXVldWUucHVzaChwcm9taXNlKTtcbiAgICB0aGlzLnByb2Nlc3NSZWdpc3RlcmVkSGFuZGxlcnMoKTtcblxuICAgIC8vIDIuMi43LiB0aGVuIG11c3QgcmV0dXJuIGEgcHJvbWlzZVxuICAgIHJldHVybiBwcm9taXNlO1xuICB9XG5cbiAgLyoqXG4gICAqIDIuMS4xLiBXaGVuIHBlbmRpbmcsIGEgcHJvbWlzZTpcbiAgICogICAyLjEuMS4xLiBtYXkgdHJhbnNpdGlvbiB0byBlaXRoZXIgdGhlIGZ1bGZpbGxlZCBvciByZWplY3RlZCBzdGF0ZS5cbiAgICogMi4xLjIuIFdoZW4gZnVsZmlsbGVkLCBhIHByb21pc2U6XG4gICAqICAgMi4xLjIuMS4gbXVzdCBub3QgdHJhbnNpdGlvbiB0byBhbnkgb3RoZXIgc3RhdGUuXG4gICAqICAgMi4xLjIuMi4gbXVzdCBoYXZlIGEgdmFsdWUsIHdoaWNoIG11c3Qgbm90IGNoYW5nZS5cbiAgICogMi4xLjMuIFdoZW4gcmVqZWN0ZWQsIGEgcHJvbWlzZTpcbiAgICogICAyLjEuMy4xLiBtdXN0IG5vdCB0cmFuc2l0aW9uIHRvIGFueSBvdGhlciBzdGF0ZS5cbiAgICogICAyLjEuMy4yLiBtdXN0IGhhdmUgYSByZWFzb24sIHdoaWNoIG11c3Qgbm90IGNoYW5nZS5cbiAgICpcbiAgICogQHBhcmFtIHN0YXRlIHN0YXRlIHRvIHRyYW5zaXRpb24gdG9cbiAgICogQHBhcmFtIHZhbHVlIHZhbHVlIHBhc3NlZCB3aXRoIHRoZSB0cmFuc2l0aW9uIGZvclxuICAgKi9cbiAgcHVibGljIHRyYW5zaXRpb25TdGF0ZShzdGF0ZTogUHJvbWlzZVN0YXRlLCB2YWx1ZTogYW55KTogdm9pZCB7XG5cbiAgICBpZiAodGhpcy5zdGF0ZSA9PT0gc3RhdGUgfHwgdGhpcy5zdGF0ZSAhPT0gUHJvbWlzZVN0YXRlLlBFTkRJTkcpIHtcbiAgICAgIC8vIGlmIHRoZSBjdXJyZW50IHN0YXRlIGlzIHNhbWUgYXMgdGhlIHN0YXRlIGJlaW5nIHRyYW5zaXRpb25lZCB0b1xuICAgICAgLy8gb3IgdGhlIHByb21pc2UgaXMgbm90IGN1cnJlbnRseSBpbiBwZW5kaW5nIHN0YXRlXG4gICAgICAvLyBkbyBub3RoaW5nXG4gICAgICByZXR1cm47XG4gICAgfVxuXG4gICAgdGhpcy52YWx1ZSA9IHZhbHVlO1xuICAgIHRoaXMuc3RhdGUgPSBzdGF0ZTtcblxuICAgIHRoaXMucHJvY2Vzc1JlZ2lzdGVyZWRIYW5kbGVycygpO1xuICB9XG5cbiAgLyoqXG4gICAqIHJlamVjdFxuICAgKiBAcGFyYW0gcmVhc29uIGNhbiBieSBhbnl0aGluZyBidXQgZ2VuZXJhbGx5IGFuIEVycm9yIG9iamVjdFxuICAgKi9cbiAgcHVibGljIHJlamVjdChyZWFzb246IEVycm9yfGFueSk6IHZvaWQge1xuICAgIHRoaXMudHJhbnNpdGlvblN0YXRlKFByb21pc2VTdGF0ZS5SRUpFQ1RFRCwgcmVhc29uKTtcbiAgfVxuXG4gIHByaXZhdGUgcHJvY2Vzc1JlZ2lzdGVyZWRIYW5kbGVycygpOiB2b2lkIHtcbiAgICBpZiAodGhpcy5zdGF0ZSAhPT0gUHJvbWlzZVN0YXRlLlBFTkRJTkcpIHtcbiAgICAgIC8vIDIuMi40IG9uRnVsZmlsbGVkIG9yIG9uUmVqZWN0ZWQgbXVzdCBub3QgYmUgY2FsbGVkXG4gICAgICAvLyB1bnRpbCB0aGUgZXhlY3V0aW9uIGNvbnRleHQgc3RhY2sgY29udGFpbnMgb25seSBwbGF0Zm9ybSBjb2RlLlxuICAgICAgc2V0VGltZW91dCgoKSA9PiB7XG5cbiAgICAgICAgLy8gMi4yLjcuIHRoZW4gbWF5IGJlIGNhbGxlZCBtdWx0aXBsZSB0aW1lcyBvbiB0aGUgc2FtZSBwcm9taXNlLlxuICAgICAgICAvLyAgIDIuMi42LjEuIElmL3doZW4gcHJvbWlzZSBpcyBmdWxmaWxsZWQsXG4gICAgICAgIC8vICAgICBhbGwgcmVzcGVjdGl2ZSBvbkZ1bGZpbGxlZCBjYWxsYmFja3MgbXVzdCBleGVjdXRlIGluIHRoZVxuICAgICAgICAvLyAgICAgb3JkZXIgb2YgdGhlaXIgb3JpZ2luYXRpbmcgY2FsbHMgdG8gdGhlbi5cbiAgICAgICAgLy8gICAyLjIuNi4yLiBJZi93aGVuIHByb21pc2UgaXMgcmVqZWN0ZWQsXG4gICAgICAgIC8vICAgICBhbGwgcmVzcGVjdGl2ZSBvblJlamVjdGVkIGNhbGxiYWNrcyBtdXN0IGV4ZWN1dGUgaW4gdGhlXG4gICAgICAgIC8vICAgICBvcmRlciBvZiB0aGVpciBvcmlnaW5hdGluZyBjYWxscyB0byB0aGVuLlxuICAgICAgICAvLyB0aGlzIGlzIGFjaGVpdmVkIGJ5IGRlcXVldWUgb24gRklGTyBkYXRhIHN0cnVjdHVyZSAoaS5lLiBxdWV1ZSlcbiAgICAgICAgd2hpbGUgKHRoaXMucHJvbWlzZVNldHRsZW1lbnRRdWV1ZS5sZW5ndGgpIHtcbiAgICAgICAgICAvLyBkZXF1ZXVlXG4gICAgICAgICAgY29uc3QgcHJvbWlzZTogTXlQcm9taXNlfGFueSA9IHRoaXMucHJvbWlzZVNldHRsZW1lbnRRdWV1ZS5zaGlmdCgpO1xuXG4gICAgICAgICAgdHJ5IHtcbiAgICAgICAgICAgIC8vIDIuMi41LiBvbkZ1bGZpbGxlZCBhbmQgb25SZWplY3RlZCBtdXN0IGJlIGNhbGxlZCBhcyBmdW5jdGlvbnMgKGkuZS4gd2l0aCBubyB0aGlzIHZhbHVlKS5cbiAgICAgICAgICAgIGNvbnN0IHZhbHVlID0gKFxuICAgICAgICAgICAgICB0aGlzLnN0YXRlID09PSBQcm9taXNlU3RhdGUuRlVMRklMTEVEID8gcHJvbWlzZS5vbkZ1bGZpbGxlZCA6IHByb21pc2Uub25SZWplY3RlZFxuICAgICAgICAgICAgKSh0aGlzLnZhbHVlKTtcbiAgICAgICAgICAgIC8vIDIuMi43LjEuIElmIGVpdGhlciBvbkZ1bGZpbGxlZCBvciBvblJlamVjdGVkIHJldHVybnMgYSB2YWx1ZSB4LFxuICAgICAgICAgICAgLy8gcnVuIHRoZSBQcm9taXNlIFJlc29sdXRpb24gUHJvY2VkdXJlIFtbUmVzb2x2ZV1dKHByb21pc2UyLCB4KS5cbiAgICAgICAgICAgIC8qKiBAdG9kbyBQcm9taXNlIFJlc29sdXRpb24gUHJvY2VkdXJlICovXG4gICAgICAgICAgfSBjYXRjaCAoZSkge1xuICAgICAgICAgICAgLy8gMi4yLjcuMi4gSWYgZWl0aGVyIG9uRnVsZmlsbGVkIG9yIG9uUmVqZWN0ZWQgdGhyb3dzIGFuIGV4Y2VwdGlvbiBlLFxuICAgICAgICAgICAgLy8gcHJvbWlzZTIgbXVzdCBiZSByZWplY3RlZCB3aXRoIGUgYXMgdGhlIHJlYXNvbi5cbiAgICAgICAgICAgIC8qKiBAdG9kbyBQcm9taXNlIFJlamVjdGlvbiBQcm9jZWR1cmUgKi9cbiAgICAgICAgICB9XG4gICAgICAgIH1cbiAgICAgIH0sIDApO1xuICAgIH1cbiAgfVxufVxuIl19